import { randomUUID } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, resolve, sep } from "node:path";
import { and, eq } from "drizzle-orm";
import { withContext } from "@/db/client";
import { storedObjects } from "@/db/schema";
import { env } from "@/lib/env";

/**
 * Private object storage (PRD 14.2). The local implementation writes under STORAGE_DIR, which is
 * never served by the web server. Keys are generated by the server and always start with the
 * workspace ID, so one workspace can never address another workspace's objects.
 */
export interface ObjectStore {
  put(workspaceId: string, kind: "imports" | "exports", extension: string, content: string | Uint8Array): Promise<string>;
  get(workspaceId: string, key: string): Promise<Buffer>;
  remove(workspaceId: string, key: string): Promise<void>;
}

class LocalObjectStore implements ObjectStore {
  private root = resolve(env().STORAGE_DIR);

  private pathFor(workspaceId: string, key: string): string {
    if (!key.startsWith(`${workspaceId}/`)) throw new Error("Storage key does not belong to this workspace.");
    const full = resolve(this.root, key);
    if (!full.startsWith(this.root + sep)) throw new Error("Invalid storage key.");
    return full;
  }

  async put(workspaceId: string, kind: "imports" | "exports", extension: string, content: string | Uint8Array): Promise<string> {
    const ext = extension.replace(/[^a-z0-9]/gi, "").slice(0, 8) || "bin";
    const key = `${workspaceId}/${kind}/${randomUUID()}.${ext}`;
    const full = this.pathFor(workspaceId, key);
    await mkdir(dirname(full), { recursive: true });
    await writeFile(full, content, { mode: 0o600 });
    return key;
  }

  get(workspaceId: string, key: string): Promise<Buffer> {
    return readFile(this.pathFor(workspaceId, key));
  }

  async remove(workspaceId: string, key: string): Promise<void> {
    await rm(this.pathFor(workspaceId, key), { force: true });
  }
}

/**
 * Keeps objects in PostgreSQL, under the same row-level security as every other tenant table. For
 * hosts where web requests do not share a writable disk (serverless). Objects are small: uploads
 * are capped at 10 MB and exports are text.
 */
export class DatabaseObjectStore implements ObjectStore {
  private check(workspaceId: string, key: string) {
    if (!key.startsWith(`${workspaceId}/`)) throw new Error("Storage key does not belong to this workspace.");
  }
  async put(workspaceId: string, kind: "imports" | "exports", extension: string, content: string | Uint8Array): Promise<string> {
    const ext = extension.replace(/[^a-z0-9]/gi, "").slice(0, 8) || "bin";
    const key = `${workspaceId}/${kind}/${randomUUID()}.${ext}`;
    await withContext({ workspaceId }, (tx) => tx.insert(storedObjects).values({ workspaceId, key, content: Buffer.from(content) }));
    return key;
  }
  async get(workspaceId: string, key: string): Promise<Buffer> {
    this.check(workspaceId, key);
    const [row] = await withContext({ workspaceId }, (tx) => tx.select({ content: storedObjects.content }).from(storedObjects).where(and(eq(storedObjects.workspaceId, workspaceId), eq(storedObjects.key, key))));
    if (!row) throw Object.assign(new Error("Stored object not found."), { code: "ENOENT" });
    return Buffer.from(row.content);
  }
  async remove(workspaceId: string, key: string): Promise<void> {
    this.check(workspaceId, key);
    await withContext({ workspaceId }, (tx) => tx.delete(storedObjects).where(and(eq(storedObjects.workspaceId, workspaceId), eq(storedObjects.key, key))));
  }
}

let store: ObjectStore | undefined;
export function objectStore(): ObjectStore {
  store ??= env().STORAGE_DRIVER === "database" ? new DatabaseObjectStore() : new LocalObjectStore();
  return store;
}
