import { randomUUID } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, resolve, sep } from "node:path";
import { env } from "@/lib/env";

/**
 * Private object storage (PRD 14.2). The local implementation writes under STORAGE_DIR, which is
 * never served by the web server. Keys are generated by the server and always start with the
 * workspace ID, so one workspace can never address another workspace's objects.
 */
export interface ObjectStore {
  put(workspaceId: string, kind: "imports" | "exports", extension: string, content: string | Uint8Array): Promise<string>;
  get(workspaceId: string, key: string): Promise<Buffer>;
  remove(workspaceId: string, key: string): Promise<void>;
}

class LocalObjectStore implements ObjectStore {
  private root = resolve(env().STORAGE_DIR);

  private pathFor(workspaceId: string, key: string): string {
    if (!key.startsWith(`${workspaceId}/`)) throw new Error("Storage key does not belong to this workspace.");
    const full = resolve(this.root, key);
    if (!full.startsWith(this.root + sep)) throw new Error("Invalid storage key.");
    return full;
  }

  async put(workspaceId: string, kind: "imports" | "exports", extension: string, content: string | Uint8Array): Promise<string> {
    const ext = extension.replace(/[^a-z0-9]/gi, "").slice(0, 8) || "bin";
    const key = `${workspaceId}/${kind}/${randomUUID()}.${ext}`;
    const full = this.pathFor(workspaceId, key);
    await mkdir(dirname(full), { recursive: true });
    await writeFile(full, content, { mode: 0o600 });
    return key;
  }

  get(workspaceId: string, key: string): Promise<Buffer> {
    return readFile(this.pathFor(workspaceId, key));
  }

  async remove(workspaceId: string, key: string): Promise<void> {
    await rm(this.pathFor(workspaceId, key), { force: true });
  }
}

let store: ObjectStore | undefined;
export function objectStore(): ObjectStore {
  store ??= new LocalObjectStore();
  return store;
}
