#!/usr/bin/env node
// Creates a local .env with freshly generated development secrets. Never overwrites an existing file.
import { existsSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";

if (existsSync(".env")) {
  console.log(".env already exists; leaving it untouched.");
  process.exit(0);
}
const secret = (n = 24) => randomBytes(n).toString("base64url");
const port = 54329;
const ownerPw = secret();
const appPw = secret();
const env = `# Generated by scripts/setup-env.mjs for local development. Do not commit.
PG_LOCAL_PORT=${port}
DATABASE_ADMIN_URL=postgres://catalog_owner:${ownerPw}@127.0.0.1:${port}/catalog_intelligence
DATABASE_URL=postgres://catalog_app:${appPw}@127.0.0.1:${port}/catalog_intelligence
BETTER_AUTH_SECRET=${secret(32)}
APP_BASE_URL=http://localhost:3000
SEED_USER_PASSWORD=${secret(12)}
AI_PROVIDER_MODE=demo
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
AI_MODEL_ID=
STORAGE_DIR=.data/storage
JOB_CONCURRENCY=2
JOB_TOKEN_CAP=400000
JOB_SPEND_CAP_USD=5
DAILY_WORKSPACE_SPEND_CAP_USD=20
`;
writeFileSync(".env", env, { mode: 0o600 });
console.log("Wrote .env with generated local secrets (seed sign-in password is SEED_USER_PASSWORD).");
